version: '3'

services:
  apache:
    image: 'php_ext'
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - "./app:/var/www/html"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysql
    volumes:
      #- "db_data:/var/lib/mysql"
      - "./database:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db_data: