version: '3'

services:
  app:
    image: 'react_img'
    container_name: react_img
    restart: always
    ports:
     - '3000:3000'
    volumes:
     - './react-app:/app'
     - './react-app/app/node_modules'
    
  apache:
    image: 'php_ext'
    container_name: php
    restart: always
    ports:
      - '8080:80'
    volumes:
      - "./php-app:/var/www/html"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysql
    volumes:
      #- "db_data:/var/lib/mysql"
      - "./mysql/database:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      
  web:
    image: nginx
    volumes:
      - ./nginx-app:/usr/share/nginx/html
    ports:
      - "80:80"
   
volumes:
  db_data: